#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password

# global settings
yabai -m config external_bar                 all:26:0	
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             first_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xaad1ff33	
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50

# general space settings
yabai -m config layout                       stack
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 10
yabai -m config right_padding                0

# mission-control desktop labels
yabai -m space 1 --label tools
yabai -m space 2 --label terminal
yabai -m space 3 --label web
yabai -m space 4 --label code

# window rules
yabai -m rule --add app="^Code" space=code
yabai -m rule --add app="^Iterm" space=terminal
yabai -m rule --add app="^Google Chrome" space=web
yabai -m rule --add app="^Slack" space=tools
yabai -m rule --add app="^Spotify$" space=tools
yabai -m rule --add app="^zoom\." space=tools
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_destroyed action="echo \"destroyed window with id \$YABAI_WINDOW_ID\""
yabai -m signal --add event=space_changed action="echo \"changed space \$YABAI_RECENT_SPACE_ID -> \$YABAI_SPACE_ID\""
yabai -m signal --add event=space_changed action="yabai -m window --focus mouse || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
echo "yabai configuration loaded.."n
