#!/usr/bin/env sh

# *yabai --load-sa* is configured to run through sudo without a password
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config external_bar                 all:26:0	
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             first_child
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50

# general space settings
yabai -m config layout                       stack
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 10
yabai -m config right_padding                0

reset-yabai-spaces

# window rules
yabai -m rule --add app="^kitty" space=4 
yabai -m rule --add app="^Google Chrome" space=3
yabai -m rule --add app="^Slack" space=1
yabai -m rule --add app="^Spotify$" space=1
yabai -m rule --add app="^Messages" space=1
yabai -m rule --add app="^zoom\." space=1
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Stickies" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_destroyed action="echo \"destroyed window with id \$YABAI_WINDOW_ID\""
yabai -m signal --add event=space_changed action="echo \"changed space \$YABAI_RECENT_SPACE_ID -> \$YABAI_SPACE_ID\""
yabai -m signal --add event=space_changed action="yabai -m window --focus mouse || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
echo "yabai configuration loaded.."n
